server:
  port: 8883
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/i_cinema
    userName: root
    password: root
  jpa: 
    hibernate.ddl-auto: update
  application:
    name: BookingMS
  cloud:
    consul:
      host: localhost
      discovery:
        hostname: localhost
        
General: 
  EXCEPTION_MESSAGE: Something went wrong!
  
BookingService:
  BOOKING_NOT_FOUND: Booking details not found!