server:
  port: 8083
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/i_cinema
    userName: root
    password: 
  jpa: 
    hibernate.ddl-auto: update
  application:
    name: TheatreMS
  cloud:
    consul:
      host: localhost
      discovery:
        hostname: localhost
        
        
General: 
  EXCEPTION_MESSAGE: Something went wrong!
  
TheatreService:
  THEATRE_NOT_FOUND: Theatre not found!
  THEATRES_NOT_FOUND: Theatres not found for given date and movie!