version: '3.8'

services:
  dbservice:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - icinema-moviesbootapp

  appservice:
    build: .
    depends_on:
      - dbservice
    environment:
      - spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://dbservice:3306/i_cinema?createDatabaseIfNotExist=true
      - spring.datasource.userName=root
      - spring.datasource.password=root
      - spring.cloud.consul.host=host.docker.internal
    ports:
      - 8882:8882
    networks:
      - icinema-moviesbootapp

volumes:
  mysql_data:

networks:
  icinema-moviesbootapp:

